### ISSUE TITLE
Fable support clarification

### ISSUE THREAD

**Issue by gaku-sei** [fsprojects/FSharpPlus#385] opened 2020-10-26 07:18 UTC
I'm pretty new to F#, and since I have a rather FP background, I really wanted to try FSharpPlus with the Fable compiler. But it turns out most of the common functions are not supported by Fable (like the Functor "type class" for instance: https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus/Control/Functor.fs#L58), and I wondered why.

Doesn't the Fable compiler offer the exact same features (minus the API) as the .Net one? If not, does the new Fable 3 version improve the potential support in any way?

Also, do you think it would possible to add a tag/label to the functions in the [API](http://fsprojects.github.io/FSharpPlus/reference/index.html)? So that the developers can see which function can be used with Fable without looking for it in the source code 😅  It'd be especially useful for those who use Ionide with VS Code, as the code compiles fine in the IDE, but fails to compile using Fable.

**Comment by wallymathieu** [comment] 2020-10-26 07:40
The Fable compiler does not understand some of the mechanism that are used in order to make generic operators. The extensions should be usable though.

It would be possible to tag and label the different parts of the API. I think @adz has put some thought into that.

**Comment by gusty** [comment] 2020-10-27 07:32
> Doesn't the Fable compiler offer the exact same features (minus the API) as the .Net one? If not, does the new Fable 3 version improve the potential support in any way?

No, it doesn't.

The problem is that Fable does a simple overload resolution while F# compiler does a very complex one.
It makes no sense for Fable to mimic the whole overload resolution from the F# compiler, instead what would happen is that the new F# compiler will store the witness in the AST so Fable (ideally Fable v3) is able to pick it up directly.

Once this happens, almost all functions of this library would work in Fable.

For the moment you can make use of almost all extensions defined here in Fable, but for more generic code you'll have to wait a bit.

**Comment by gaku-sei** [comment] 2020-10-27 09:36
Thank you very much for your reply @gusty @wallymathieu that's really good to know. In my mind Fable had the same feature set 🤔 
Out of curiosity, do you know if there is any documentation regarding the "missing" features in the Fable compiler?

>what would happen is that the new F# compiler will store the witness in the AST so Fable (ideally Fable v3) is able to pick it up directly

I thought it already worked that way actually (more or less what js_of_ocaml does for instance, compiling down to an AST, and then transforming the AST to JS). That's also very good to know it's something that could happen one day 😄 

>For the moment you can make use of almost all extensions defined here in Fable, but for more generic code you'll have to wait a bit.

Sure, makes sense. I also asked the question to have a bit more insight into the Fable compiler limitations before starting to work on a "bigger" project.

>It would be possible to tag and label the different parts of the API. I think @adz has put some thought into that.

Thank you very much 😄

**Comment by gusty** [comment] 2021-07-01 05:43
I'll close this issue, Fable 3 is a real thing now.

Still, there's some differences in overload resolution, there is no documentation about it AFAIK, probably because there are still big efforts in improving the situation with many Fable 3 updates.

To keep tuned, look at Fable issue related to witness passing, trait calls and SRTPs.

**Closed by gusty** 2021-07-01 05:43 UTC
Labels: question
