### ISSUE TITLE
Overlap with FSharpx.Extras

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharpPlus#139] opened 2018-10-31 13:36 UTC
On the surface there seems to be a bit over overlap between FSharpPlus and FSharpx.Extras, but I can't find any documentation or comments on this anywhere. What is the relationship between the two libraries? Are they as similar as they may seem at first glance?

**Comment by wallymathieu** [comment] 2018-10-31 14:03
Part of it is different focus. FSharpx.Extras implements things differently and with a different style of f#. The [lens definition](https://github.com/fsprojects/FSharpx.Extras/blob/master/src/FSharpx.Extras/Lens.fs) for instance. 

I've used FSharpx.Extras to help with interop with f# from c# for instance.

**Comment by gusty** [comment] 2018-10-31 14:06
Back in time, when FSharpX was created I worked in a PR which was never merged.
So we decided to create a separate library and see how it goes.
Nowadays FSharpX was split in different pieces.
Actually now FSharpX Collections could be very easily integrated with FSharpPlus, without even adding a dependency. You just need to add the required methods and you can hide them from the tooling as @wallymathieu  did with https://github.com/fsprojects/FSharpPlus/commits/master/src/FSharpPlus/DList.fs

**Comment by cmeeren** [comment] 2018-10-31 16:12
Thanks for the clarifications. Are you saying that feature-wise there's a significant overlap, but implementation- and usage-wise it's different?

(The question is made a bit harder by the fact that FSharpx seem to have no documentation outside of API reference.)

**Comment by gusty** [comment] 2018-10-31 16:43
Well there are also some conceptual differences.

This library tries to keep the scope as "an extension of FSharp.Core" whereas FSharpX seems to have passed beyond that limit long time ago.

Nowadays it feels like many people was dropping stuff there and it's a big repository of common code for different purposes.

Documentation is a top priority here, we worked a lot with the different samples and we still need more stuff in some areas.

Once you know how it works it becomes very handy, I almost start every single script by linking it :)

**Comment by wallymathieu** [comment] 2018-10-31 17:06
Compare monoid in fsharp x : https://github.com/fsprojects/FSharpx.Extras/blob/master/src/FSharpx.Extras/Monoid.fs with how similar abstractions are implemented in f#+

**Comment by wallymathieu** [comment] 2018-12-16 17:59
@cmeeren what are your thoughts? Have you gotten an impression of what the differences are?

Perhaps FSharpX could do with some clean up?

**Comment by wallymathieu** [comment] 2019-01-02 11:56
Since there is not anything new here, perhaps time to close the issue.

**Closed by wallymathieu** 2019-01-02 11:56 UTC
Labels: discussion

**Comment by aammfe** [comment] 2020-08-11 02:58
> I haven't tried FSharpPlus or FSharpX yet. I have a fairly good idea of how I want to use FSharpPlus, but the Intellisense performance impact means I have to experiment a bit to see if it's worth it. It's on my todo-list, though very low as I'm busy with other higher-priority programming tasks. As for FSharpX, I currently have no concrete plans of trying it.

so after 2+ years can u please share ur experience ?

**Comment by cmeeren** [comment] 2020-08-11 05:23
I have used FSharpPlus for maybe a year now, and I can't really imagine going back. For me it's a core part of F# now. Very happy with it. Intellisense performance is fine as long as you don't define too many "ultra-generic" functions yourself.

**Comment by texastoland** [comment] 2021-08-05 14:09
# Overlap with FSharpx.Extras #139

I landed here googling <samp>fsharpx vs fsharpplus</samp>. My functional background is Elm, PureScript, OCaml, and now Fable. Neither F#<strong>+</strong> nor F#<strong>x</strong> immediately recall Haskell's Prelude and its functor-applicative-monad hierarchy. [Higher](https://github.com/palladin/Higher) does but it's unpublished, unmaintained, and [<q>not intended for production use</q>](https://github.com/palladin/Higher). Here are my observations:

## F#<em>x</em> (the other library)

- At first glance the [`Monoid` class](https://github.com/fsprojects/FSharpx.Extras/blob/master/src/FSharpx.Extras/Monoid.fs) parallels Haskell's but there are no other type classes to be found.
- Modules like [`Option`](https://github.com/fsprojects/FSharpx.Extras/blob/master/src/FSharpx.Extras/ComputationExpressions/Option.fs) contain type class instances.
- Builder classes like `MaybeBuilder` serve as ad-hoc monad instances.
- Modules additionally include non-generic versions of functions like `ap`.
- `ap` uses the [default monad implementation](https://github.com/fsprojects/FSharpx.Extras/blob/master/src/FSharpx.Extras/ComputationExpressions/Option.fs) that isn't parallelizable.

## F#<em>+</em>

- At first glance https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus/Control/Monoid.f is unrecognizable from Haskell. Instead each type class method is implemented as its own F# class.
- Each method provides a generic version and numerous specialized overrides.
- Methods sometimes use operator names and type parameters utilizing type-like annotations between double backticks like <code>'``Monad<'T * 'U * 'V>``</code>.
- Builders are generic with variations like strict vs. lazy and support parallelizable [applicative computation expressions](https://devblogs.microsoft.com/dotnet/announcing-f-5-preview-1/?utm_source=pocket_mylist#applicative-computation-expressions).
- Applicative functors however are [incorrectly implemented](F#<strong>x</strong>) identically to F#x. **Is this a bug**?  I think it could be resolved by implementing both applicative instances and computation expressions in terms of [the monoidal presentation]( https://en.m.wikibooks.org/wiki/Haskell/Applicative_functors#The_monoidal_presentation).
- F#<strong>+</strong> additionally supports [Fable compilation](https://fable.io/repl/) (#121).

**Comment by cmeeren** [comment] 2021-08-05 14:27
For the record, I no longer stand by [my comment just above](https://github.com/fsprojects/FSharpPlus/issues/139#issuecomment-671732717). As I have previously mentioned in https://github.com/fsprojects/FSharpPlus/issues/11#issuecomment-713097983, extensively using generic functions like `map` significantly impacts Intellisense performance. In my solutions, it ended up increasing intellisense update lag to >10s, which is completely unworkable for me. I therefore chose to abandon FSharpPlus not long after I made the comment above. This refactor dramatically improved the Intellisense performance. I haven't really missed it that much; I use [Aether](https://github.com/xyncro/aether) for lenses, write things like `traverse` myself as I need them (I normally only need `Option.traverseAsync`), and live well with non-generic functions `List.map` etc.

**Comment by gusty** [comment] 2021-08-05 15:26
@texastoland  Thanks for your comments, btw do you have a more specific question?

Contrary to what most people believe, F#+ doesn't aim to reproduce Haskell, so yes there are differences as this library is aimed for F# use and also due to limitations of the language (namely the type system) we can't be as generic as Haskell is without paying a price, @cmeeren already mentioned slow compiling times, that's one of the problems.

Also for the record, we're hardly adding more generic abstractions to the library, for the reasons above mentioned, we're focusing more on usability by giving options to specialize the code (as we did in the latest versions with specialized computation expressions) and getting better Fable support. This way we don't force our users to use generic code, that was never the goal of this library.

Generic functions won't play a key role in future versions, we won't remove them and we'll keep improving them but for instance they won't open automatically.

I think F#x is a similar effort, but it focus more on different collections, in terms of maintenance I would say this library is more actively maintained and has a relative good record of maintenance over the years.

> Applicative functors however are incorrectly implemented identically to F#x. Is this a bug? I think it could be resolved by implementing both applicative instances and computation expressions in terms of the monoidal presentation.

Can you please explain what is the applicative functor bug? The link you sent doesn't take you anywhere, or even better please open a separate issue.

**Comment by texastoland** [comment] 2021-08-06 00:06
> btw do you have a more specific question?

Just making observations for anyone else who finds this issue googling.

> F#+ doesn't aim to reproduce Haskell

I agree with that premise. I was actually just looking for a library of common builders. I reached for FsToolkit.ErrorHandling but found your [SO answer](https://stackoverflow.com/a/64281243).

> The link you sent doesn't take you anywhere

Oops for example https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus/Extensions/Async.fs

> Can you please explain what is the applicative functor bug?

It's sequential so you couldn't use it to implement applicative computation expressions for example. I think it'd be easier to implement applicative instances with `return`/`pure`/`unit` and `merge`/`both`/`*&*` (the monoidal presantation used in both applicative computation expressions and OCaml's new syntax) and derive `apply` from that instead of `bind`. Also `mapN` should use `and!`.

**Comment by gusty** [comment] 2021-08-06 08:16
> That makes sense. It looks like F#x underwent a similar change.

Yes, but here we're not planning to change anything, generic functions would still be fully supported. I use them a lot for instance in places where compile time doesn't matter too much.

Regarding the "bug" you mention, I don't think it's a bug:

 - Async doesn't imply parallel, there are many discussions about why implicit parallelism is a bad idea. See https://github.com/dotnet/fsharp/issues/10301
 - Whether to default `<*>` to `bind` / `return` or `merge` is a design decision, not a bug as no alternative is wrong, both are valids. However I would be interested in experimenting with both and eventually if it worth switching in F#+ 2.0 so if you can summarize pros and cons please let me know (maybe open a separate issue).
 
The right way to generalize over parallel asyncs is to wrap Asyncs in a type which has a different applicative instance for that, see #36

**Comment by texastoland** [comment] 2021-08-06 08:40
That's definitely the relevant issue. My bad for not searching. I disagree with the feedback but see it was well thought out 👌🏼 As for the benefits of `merge` it just aligns more closely with computation expressions, easier to get them "right" if right is parallelized (by not accidentaly defaulting to the monadic derivation), and generally easier to understand and implement.
