### ISSUE TITLE
`(>>=)` should be constrained with `Map`

### ISSUE THREAD

**Issue by xgrommx** [fsprojects/FSharpPlus#497] opened 2022-09-06 20:32 UTC
Hello,`Monad` should be restricted with `Map`

Here
```fsharp
type Maybe<'a> =
   | Just of 'a
   | Nothing 

let maybeMap f m = match m with
  | Just x -> Just (f x)
  | Nothing -> Nothing

//type Maybe<'a> with
//  static member Map (x: Maybe<'a>, f: 'a -> 'b) = maybeMap f x

//let r2' = map (fun x -> x + 1.0) (Just 10.0)

let maybeBind f m = match m with
  | Just x -> f x
  | Nothing -> Nothing

type Maybe<'a> with
  static member (>>=) (x: Maybe<'a>, f: 'a -> Maybe<'b>) = maybeBind f x

let r2'' = Just 10 >>= fun x -> Just (x + 10)
```

Should  throw error that, `Maybe` doesn't have property `Map`, because `Monad` should be restricted with `Map`
But probably should be `Functor <= Applicative <= Monad`

**Comment by gusty** [comment] 2022-09-06 22:47
Thanks for submitting this issue !

I don't get it 100%

I think you mean that a Monad is either:

- Bind and Return: and Return here it's missing
or
 - Join and Map: and if instead of Bind we define Join, Map would be missing

In anycase, FSharpPlus is not a strict typeclass library.
We get inspiration from them but the goal is not to copy.
We're happy in defining abstractions that accept ony one operation, they will have some limitations of course but as you can see in your own example, they can still be useful.

If that's what you're claiming, i would say: this is by design.
Please clarify

**Comment by xgrommx** [comment] 2022-09-08 20:40
@gusty I mean that we cannot write `Monad` if it isn't `Applicative` and `Functor`, of course we can derive it via `Monad` b some laws and rules. My question was, how can I create some new typeclass with restriction on type that it should be `Monad`

**Comment by xgrommx** [comment] 2022-09-09 18:55
@cannorin But maybe we can create more readable error text?

**Comment by cannorin** [comment] 2022-09-09 19:37
@xgrommx  It's very difficult because F#'s constraint solver is rather limited: The F# compiler only knows that something is missing but doesn't know what is actually missing. FSharpPlus is just a library that tries to simulate type classes in F#, so we have almost no control over how the error messages are reported.

You can think of FSharpPlus's type classes as some kind of "emulation": it is useful but not a real type class. If you are learning about type classes, or having type classes as a first-class language feature is your priority, I guess you should better use another language.

**Comment by gusty** [comment] 2022-09-09 21:09
Anyways, that error is not that confusing.
If you add such overload it should work, the only thing is that it won't tell which other options you have, like adding `Return` and defaulting to monads.

**Comment by xgrommx** [comment] 2022-09-10 14:23
@cannorin I know haskell, purescript, etc

**Comment by cannorin** [comment] 2022-09-10 14:45
Then you would need to accept that:

* F# is not a language that comes with a first-class support of type classes.
* FSharpPlus is not a language extension, and only provides an "emulated" version of type classes.
* Therefore, the user experience on FSharpPlus's type classes may not be as good as that of Haskell of PureScript.

I'm closing this issue because I don't think this leads to a constructive discussion. I repeat my last message: if having type classes as a first-class language feature (i.e. more strict instance checks, more natural error messages, etc) is your priority, I guess you should better use some other languages.

**Closed by cannorin** 2022-09-10 14:45 UTC
