### ISSUE TITLE
F# compile error "FS0073 internal error: Undefined or unsolved type variable" when using custom monad with monad CE

### ISSUE THREAD

**Issue by Hong-Xiang** [fsprojects/FSharpPlus#458] opened 2021-07-08 03:10 UTC
### Description

When using a custom monad and built-in `monad` CE, compile failed.

### Repro steps
```f#
open FSharpPlus

type Op<'a> =
    | S of 'a
    | N

    static member Return(x: 'a) : Op<'a> = S x

    static member (>>=)(x: Op<'a>, f: 'a -> Op<'b>) : Op<'b> =
        match x with
        | N -> N
        | S (x') -> f x'

let test : Op<int> =
    monad {
        let! a = S 40
        let! b = S 2
        return a + b
    }
```

### Expected behavior

Compile succeed

### Actual behavior

Compile failed with FS0073, FS0073 internal error: Undefined or unsolved type variable.

### Related information 

* Operating system: Win 10
* Branch FSharp v 1.2.0
* .NET Runtime, CoreCLR or Mono Version : Net 5.0

**Comment by gusty** [comment] 2021-07-09 04:25
Interesting, that shouldn't happen I have to investigate if is always the case or if there is a regression (library or compiler) involved.

Anyway, the problem seems to be that your monad is not lazy, so you should use the strict version, if you do so it will work:

```
let test : Op<int> =
    monad' {
        let! a = S 40
        let! b = S 2
        return a + b
    }
```

**Comment by gusty** [comment] 2021-07-10 07:28
This is not a regression, this is rather another case where using the same type parameter for the type and the static member confuses F# type inference. This practice is not recommended, I always advice to avoid using the same parameter and when I write code I adopt a convention that force me to do that, like using lower case in the type and uppercase in the static members or the other way around.

Somehow, using the correct builder makes your code work, but you might get failures somewhere else, so please write something like this instead:

```
type Op<'A> =
    | S of 'A
    | N

    static member Return(x: 'a) : Op<'a> = S x

    static member (>>=)(x: Op<'a>, f: 'a -> Op<'b>) : Op<'b> =
        match x with
        | N -> N
        | S (x') -> f x'

let test : Op<int> =
    monad {
        let! a = S 40
        let! b = S 2
        return a + b
    }
```

We should stress in our docs to avoid that practice.

**Comment by Hong-Xiang** [comment] 2021-07-10 09:32
Thanks for your helpful advice. By following your suggestion the problem is solved. Should this issue be closed?

**Comment by wallymathieu** [comment] 2021-07-10 10:25
Is this something that could be documented so that it could help people having similar issues?

**Comment by gusty** [comment] 2021-07-10 15:45
Yes, although this is a general F# issue, not specific to this library but to F# statically constraining parameters.

We should add some tips section somewhere as there are other recommendations to follow and people not familiar with it, falls in those traps as well.

Closing this one.

**Closed by gusty** 2021-07-10 15:45 UTC
